#!/bin/sh

ICONV_CUE_F=
ICONV_CUE_T=UTF8
# replace to "iconv" if want use iconv by default. Now use enconv (enca)
# require enca: http://gitorious.org/enca
ICONV_TYPE=enca

NO_ICONV=N

while getopts 'hc:t:n' OPTION
do
    case $OPTION in
    c)
        ICONV_CUE_F=$OPTARG
        ;;
    t)
        if [ "${OPTARG}" = "enca" ]; then
            ICONV_TYPE=enca
        elif [ "${OPTARG}" = "iconv" ]; then
            # FIXIT: required strict order params
            #if [ -z "$ICONV_CUE_F" ]; then
            #    echo "Param [ -c cue_encoding ] required when using iconv as conversion type"
            #    exit 2
            #fi
            ICONV_TYPE=iconv
        fi 
        ;;
    n)
        NO_ICONV=Y
        ;;
    h)
        printf "Usage: %s: [-c cue_encoding]\n" $(basename $0) >&2
        exit 2
        ;;
    esac
done

DISKNUM=
test_disk_image() {
    DISKNUM=`echo "$1" | perl -pe 's/.*(?:cd|disk)\s*(\d+).*/$1/i'`
    if [ "x$DISKNUM" = "x$1" ]; then
        DISKNUM=""
    fi
}

copy_tags_from_parent() {
    # source tag flac-file
    flacfile=$1

    if [ -n $2 ] ; then
        workdir="$2/"
    else
        workdir="./"
    fi

    # this taglist will be parsed in flac-file
    fields='TITLE VERSION ALBUM TRACKNUMBER TRACKTOTAL ARTIST PERFORMER COPYRIGHT LICENSE ORGANIZATION DESCRIPTION GENRE DATE LOCATION CONTACT ISRC'

    SOURCE_TAGS_FILE=.sourse_tag_file.$$
    TAGS_FILE=.result_tag_file.$$

    : > $SOURCE_TAGS_FILE
    for field in $fields
    do
        tag=`metaflac --show-tag=${field} "${flacfile}"`
        if [ -n "${tag}" ]; then
            echo ${tag} >> $SOURCE_TAGS_FILE
        fi
    done

    find "${workdir}" -name '*.flac' -size -100M | while read file
    do
        if [ ! -f $TAGS_FILE ] ; then
            while read line ; do
                TAG=`echo $line | awk -F= '{print $1}'`
                exist="`metaflac --show-tag="${TAG}" "${file}"`"
                if [ -z "${exist}" ] ; then
                    echo $line >> $TAGS_FILE
                fi
            done < $SOURCE_TAGS_FILE
            if [ -f $TAGS_FILE ] ; then
                `metaflac --import-tags-from="${TAGS_FILE}" "${file}"`
            fi
        fi
    done

    rm -f $SOURCE_TAGS_FILE $TAGS_FILE
}



BASEDIR=${PWD}
SAVEIFS=$IFS
IFS='\n'
WORKDIR=.tmp-split-cue-flac

find ./ -name '*.flac' -size +100M |  while read image
do
    echo "$image"
    DIR=`dirname "$image"`
    BASE=`basename "$image"`
    BASE=`echo "$BASE" | sed -e 's/.flac//'`
    CUE=$BASE.cue
    IMAGE=$BASE.flac

    cd "$DIR"
        echo "Splitting with shnsplit"
        rm -rf $WORKDIR
        mkdir $WORKDIR

        if [ "x$ICONV_TYPE" = "xiconv" ]; then
            # use iconv
            if [ "x$ICONV_CUE_F" != "x" ]; then
               echo "Converting cue (use iconv) $CUE"
               iconv -f $ICONV_CUE_F -t $ICONV_CUE_T "$CUE" -o "$WORKDIR/$CUE"
            else
               cp "$CUE" "$WORKDIR/$CUE"
            fi
        else
            # use enca
            cp "$CUE" "$WORKDIR/$CUE"
            if [ "x$ICONV_CUE_F" != "x" ]; then
               echo "Converting cue (use enconv) $CUE"
               enconv -x $ICONV_CUE_F "$WORKDIR/$CUE"
            elif [ "$NO_ICONV" != "Y" ]; then
               echo "Converting cue (use enconv) $CUE"
               enconv "$WORKDIR/$CUE"
            fi
        fi && \

        shnsplit -d $WORKDIR -o flac -f "$WORKDIR/$CUE" -t "%n – %t" "$IMAGE" && \

        echo "Fixing tags with cuetag" && \
        cuetag "$WORKDIR/$CUE" ./$WORKDIR/*.flac && \

        IFS=' ' && \
        echo "Copy tags from ${IMAGE} to new files" && \
        copy_tags_from_parent "${IMAGE}" "${WORKDIR}" && \
        IFS='\n' && \

        echo "Moving $IMAGE -> ${IMAGE}.image" && \
        mv "$IMAGE" "${IMAGE}.image" && \

        test_disk_image "$IMAGE" && \

        DSK= && \
        if [ "x$DISKNUM" != "x" ]; then
            DSK="CD$DISKNUM"
            echo "Creating $DSK dir"
            rm -rf $DSK
            mkdir $DSK
        fi && \

        mv $WORKDIR/*.flac ./$DSK && \

        rm -r $WORKDIR

    if [ "x$DIR" != "x." ]; then
        cd "$BASEDIR"
    fi
done
IFS=$SAVEIFS

